version: "3"

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
